--- 
- name: Accept Java 8 License
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
- name: "Adding Repositories"
  apt_repository: repo="{{ item }}" state=present
  with_items:
  - 'ppa:webupd8team/java'
  - 'ppa:webupd8team/atom'
- name: "Installing java8, eclipse"
  apt: name="{{ item }}" update_cache=yes
  with_items:
  - python-pexpect 
  - lib32z1
  - lib32ncurses5
  - libbz2-1.0:i386
  - lib32stdc++6
  - atom
  - intel-microcode
  - ubuntu-make
  - npm

- name: Installing java8
  apt: name=oracle-java8-installer
    
- name: Installing Android studio
  shell: umake android --accept-license /home/chaosnetz/Desktop/android-studio
  args:
    creates: /home/chaosnetz/Desktop/android-studio
  become: true
  become_user: chaosnetz
    
    
- name: Installing Idea Community edition
  shell: umake ide idea --accept-license /home/chaosnetz/Desktop/idea
  args:
    creates: /home/chaosnetz/Desktop/idea
  become: true
  become_user: chaosnetz

- name: Installing Eclipse JEE
  shell: umake ide eclipse-jee --accept-license /home/chaosnetz/Desktop/eclipse
  args:
    creates: /home/chaosnetz/Desktop/eclipse
  become: true
  become_user: chaosnetz

