--- 
- name: Accept Java 8 License
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
- name: "Adding Repositories"
  apt_repository: repo="{{ item }}" state=present
  with_items:
  - 'ppa:webupd8team/java'
  - 'ppa:webupd8team/atom'
- name: "Installing dependencies"
  apt: name="{{ item }}" update_cache=yes
  with_items:
  - python-pexpect 
  - lib32z1
  - lib32ncurses5
  - libbz2-1.0:i386
  - lib32stdc++6
  - atom
  - intel-microcode

- name: Installing java8
  apt: name=oracle-java8-installer

- name: Installing umake
  git:
    repo: https://github.com/ubuntu/ubuntu-make.git
    dest: /usr/local/umake
    update: yes
    clone: yes

- name: Installing Android studio
  shell: /usr/local/umake/bin/umake android --accept-license /home/chaosnetz/android
  args:
    creates: /home/chaosnetz/android
  become: true
  become_user: chaosnetz
    
    
- name: Installing Idea Community edition
  shell: /usr/local/umake/bin/umake ide idea /home/chaosnetz/idea
  args:
    creates: /home/chaosnetz/idea
  become: true
  become_user: chaosnetz

- name: Installing Eclipse JEE
  shell: /usr/local/umake/bin/umake ide eclipse-jee /home/chaosnetz/eclipse
  args:
    creates: /home/chaosnetz/eclipse
  become: true
  become_user: chaosnetz

- name: Installing NodeJS
  shell: /usr/local/umake/bin/umake nodejs /home/chaosnetz/nodejs
  args:
    creates: /home/chaosnetz/nodejs
  become: true
  become_user: chaosnetz
